estudiantes = [
    {"nombre": "Juan", "nota": 85},
    {"nombre": "Maria", "nota": 92},
    {"nombre": "Pedro", "nota": 78},
    {"nombre": "Ana", "nota": 95},
    {"nombre": "Luis", "nota": 88},
    {"nombre": "Sofia", "nota": 90},
    {"nombre": "Carlos", "nota": 82},
    {"nombre": "Lucia", "nota": 91},
    {"nombre": "Miguel", "nota": 80},
    {"nombre": "Isabel", "nota": 94},
    {"nombre": "Diego", "nota": 87},
    {"nombre": "Valentina", "nota": 89},
    {"nombre": "Santiago", "nota": 83},
    {"nombre": "Camila", "nota": 93},
    {"nombre": "Matias", "nota": 81},
    {"nombre": "Gabriela", "nota": 90},
    {"nombre": "Andres", "nota": 86},
    {"nombre": "Natalia", "nota": 92},
    {"nombre": "Javier", "nota": 84},
    {"nombre": "Laura", "nota": 91},
    {"nombre": "Fernando", "nota": 88},
]
