estudiantes = [
    {"nombre": "Juan", "nota": 85},
    {"nombre": "Juan", "nota": 85},
    {"nombre": "María", "nota": 92},
    {"nombre": "Pedro", "nota": 78},
    {"nombre": "Ana", "nota": 95},
    {"nombre": "Luis", "nota": 88},
    {"nombre": "Sofía", "nota": 90},
    {"nombre": "Carlos", "nota": 82},
    {"nombre": "Lucía", "nota": 91},
    {"nombre": "Miguel", "nota": 80},
    {"nombre": "Isabel", "nota": 94},
    { "nombre": "Diego", "nota": 87},
    { "nombre": "Valentina", "nota": 89},
    { "nombre": "Santiago", "nota": 83},
    { "nombre": "Camila", "nota": 93},
    { "nombre": "Matías", "nota": 81},
    { "nombre": "Gabriela", "nota": 90},
    { "nombre": "Andrés", "nota": 86},
    { "nombre": "Natalia", "nota": 92},
    { "nombre": "Javier", "nota": 84},
    { "nombre": "Laura", "nota": 91},
    { "nombre": "Fernando", "nota": 88},
    { "nombre": "Sofía", "nota": 89},
    { "nombre": "Diego", "nota": 85},
    { "nombre": "Valentina", "nota": 90},
    { "nombre": "Santiago", "nota": 82},
    { "nombre": "Camila", "nota": 94},
    { "nombre": "Matías", "nota": 80},
    { "nombre": "Gabriela", "nota": 91},
    { "nombre": "Andrés", "nota": 87},
    { "nombre": "Natalia", "nota": 93},
    { "nombre": "Javier", "nota": 83},
    { "nombre": "Laura", "nota": 92},
]